server:
  port: 8081

fiap:
  debug: false

spring:
  datasource:
    url: jdbc:h2:~/Documents/42scjcerveja;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  h2:
    console:
      enabled: true # localhost:8081/h2-console
  jpa:
    hibernate:
      ddl-auto: update # Remover quando implementar migrations