spring.data.mongodb:
  host: ${MONGODB_HOST:localhost}
  port: ${MONGODB_PORT:27017}
  database: ${MONGODB_DATABASE:db_findbar}
  username: ${MONGODB_USERNAME:admin}
  password: ${MONGODB_PASSWORD:admin}
  authentication-database: ${MONGODB_AUTH_DATABASE:admin}